channels:
- conda-forge
- patrikhlobil
dependencies:
- aiohttp
- conda-merge
- fsspec
- geopandas >=0.10.0
- invoke
- ipykernel
- lxml
- odfpy
- openpyxl
- osmnx
- pandas
- pandas-bokeh
- pandera
- pip
- ploomber
- pyarrow
- pygeos
- python-dotenv
- requests
- s3fs
- scikit-learn
- seaborn
- tqdm
- pip:
  - codema-dev-tasks==0.2.0
  - rcbm
name: codema-dev-projects
